export type CreateParcelOrder = {
  senderName: string;
  senderSurname: string;
  senderPostCode: string;
  senderCity: string;
  senderAdress: string;
  senderCountry: string;
  name: string;
  surname: string;
  city: string;
  country: string;
  adress: string;
  postCode: string;
  amount: number;
  cashOnDelivery: boolean;
  clientEmail?: string;
  phone?: string;
  numberOfParcel?: string;
  deliveryCode?: string;
  isMarked?: boolean;
  isMarkedVERIFICATION?: boolean;
  amountOfTrials?: number;
  isDeliveryCode?: boolean;
  noAddressee?: boolean;
  placeOfLeavingParcel?: string;
  status?: {
    name: string;
    createdAt: String;
    subject?: string;
    details?: string;
    isSignature?: boolean;
    signature?: string;
    deliveryInput?: string | null;
    noAddressee?: boolean;
    reasonOfAdvice?: string;
    officeOfAdvice?: string;
    placeOfNotification?: string;
  }[];
  isDownloaded?: boolean;
  forUser?: string;
  isBooked?: boolean;
  numberOfBook?: string;
  _id?: string;
};
